#server:
#  port: 9412
#spring:
#  application:
#    name: zipkin-server
##  main:
##    allow-bean-definition-overriding: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#    appname: zipkin-server
#    hostname: localhost
#    non-secure-port: 8761
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
#  metrics:
#    web:
#      server:
#        auto-time-requests: false

################################################

# 服务端口
server:
  port: 9412

spring:
  application:
    name: zipkin-server
  security:
    user:
      name: admin
      password: 123456
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.85.179
    port: 6379
    password: 123456
  #rabbitmq配置
  rabbitmq:
    addresses: 192.168.85.179
    username: admin
    password: 123456
    virtual-host: /
    port: 15672

  #禁用sleuth
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0

  # zipkin配置
  #
  # 调用链数据源配置
  datasource:
    url: jdbc:mysql://192.168.85.210:3306/jbone_zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true

# 调用链配置mysql存储
zipkin:
  storage:
    type: mysql
    StorageComponent: mysql
  collector:
    rabbitmq:
      addresses: 192.168.85.179
      port: 15672
      username: admin
      password: 123456
      queue: zipkin

#注册中心
eureka:
  client:
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
  instance:
    #表示eureka client发送心跳给server端的频率，默认为30秒
    leaseRenewalIntervalInSeconds: 10
    #健康检查的地址（依赖spring-boot-starter-actuator）
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: localhost
  metadata-map:
    user.name: ${spring.security.user.name}
    user.password: ${spring.security.user.password}

# actuator服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        #解决zipkin异常：Prometheus requires that all meters with the same name have the same set of tag keys
        auto-time-requests: false

#turbine:
#  aggregator:
#    cluster-config: default     #需要监控的服务集群名
#  app-config: feign-invoker,eureka-provider    #需要监控的服务名
#  cluster-name-expression: new String("default")

info: #/info请求的显示信息
  app:
    name: ${spring.application.name}
    version: 1.0.0
